apiVersion: v1
kind: Pod
metadata:
  name: lr-pod1
  namespace: ns2
spec:
  containers:
  - name: container
    image: ghcr.io/wsjang5324/app
    resources:
      requests:
        memory: 0.1Gi
      limits:
        memory: 0.5Gi
