apiVersion: v1
kind: Pod
metadata:
  name: rq-pod2
  namespace: ns1
spec:
  containers:
  - name: container
    image: ghcr.io/wsjang5324/app
    resources:
      requests:
        memory: 0.5Gi
      limits:
        memory: 0.5Gi
