apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: headless-ss1
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db2
  serviceName: "headless-ss-svc"
  template:
    metadata:
      labels:
        type: db2
    spec:
      containers:
      - name: container
        image: ghcr.io/wsjang5324/app
      terminationGracePeriodSeconds: 10
