apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: stateful-rs1
spec:
  replicas: 1
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      labels:
        type: web
    spec:
      containers:
      - name: container
        image: nginx
      terminationGracePeriodSeconds: 10
