apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-ss1
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
  serviceName: "db"
  template:
    metadata:
      labels:
        type: db
    spec:
      containers:
      - name: container
        image: nginx
      terminationGracePeriodSeconds: 10
